--- 
author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-Server-SimpleSMTP
no_index: 
  directory: 
    - inc
    - t
requires: 
  Email::Address: 1.886
  Email::MessageID: 1.35
  Email::Simple: 1.998
  POE: 0.38
  POE::Component::Client::DNS: 0.99
  POE::Component::Client::SMTP: 0.13
  POE::Component::Pluggable: 0.03
  Socket: 0
version: 0.95
